/**
 * Application entry point.
 *
 * Plugin registration order:
 * 1. Pinia  — store layer (must be first; router may read stores)
 * 2. Router — navigation
 * 3. VueQuery — server-state provider (QueryClientProvider injected globally)
 * 4. PrimeVue — component library (after Tailwind base so CSS layers resolve correctly)
 *
 * CSS layer order is enforced in the HTML <head> via explicit @layer declarations.
 * Tailwind's base/components/utilities are loaded first; PrimeVue's styles
 * (imported via primevue/resources/themes/*) sit on top.
 */

import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { VueQueryPlugin, QueryClient, type VueQueryPluginOptions } from '@tanstack/vue-query'
import PrimeVue from 'primevue/config'
import App from './App.vue'
import router from './router'

// Design tokens must be imported before any component CSS so custom properties
// are available globally at parse time.
import '../design/tokens.css'
// Tailwind CSS (generated by PostCSS / Vite plugin)
import './tailwind.css'

// ---------------------------------------------------------------------------
// TanStack Query client
// ---------------------------------------------------------------------------

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      // Retry once on network errors; do not retry on 4xx (pipeline errors)
      retry: (failureCount, error) => {
        if (error instanceof Error && 'response' in error) {
          const status = (error as unknown as { response?: { status?: number } }).response?.status
          if (status !== undefined && status >= 400 && status < 500) return false
        }
        return failureCount < 1
      },
      // Stale time is intentionally short for status polling; overridden per-query
      staleTime: 10_000,
    },
  },
})

const vueQueryOptions: VueQueryPluginOptions = { queryClient }

// ---------------------------------------------------------------------------
// App bootstrap
// ---------------------------------------------------------------------------

// REVIEW-ONLY: dev API mock, active only when VITE_MOCK=1 (no-op otherwise).
if (import.meta.env.VITE_MOCK === '1') {
  const { installReviewMock } = await import('../__review_mock__/mock')
  installReviewMock()
}

const app = createApp(App)

app.use(createPinia())
app.use(router)
app.use(VueQueryPlugin, vueQueryOptions)
app.use(PrimeVue, {
  // Unstyled mode: PrimeVue renders semantic HTML without its own CSS.
  // We supply all visual styling via Tailwind + tokens.
  unstyled: false,
  // Ripple disabled — the QC dashboard aesthetic avoids Material-style effects.
  ripple: false,
})

app.mount('#app')
